// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module mailbox_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 5
) (
  input clk_i,
  input rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output mailbox_reg_pkg::mailbox_reg2hw_t reg2hw, // Write


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import mailbox_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic int_snd_status_status_qs;
  logic int_snd_status_status_wd;
  logic int_snd_status_status_we;
  logic [30:0] int_snd_status_reserved_qs;
  logic int_snd_set_set_qs;
  logic int_snd_set_set_wd;
  logic int_snd_set_set_we;
  logic [30:0] int_snd_set_reserved_qs;
  logic int_snd_clear_clear_qs;
  logic int_snd_clear_clear_wd;
  logic int_snd_clear_clear_we;
  logic [30:0] int_snd_clear_reserved_qs;
  logic int_rcv_status_status_qs;
  logic int_rcv_status_status_wd;
  logic int_rcv_status_status_we;
  logic [30:0] int_rcv_status_reserved_qs;
  logic int_rcv_set_set_qs;
  logic int_rcv_set_set_wd;
  logic int_rcv_set_set_we;
  logic [30:0] int_rcv_set_reserved_qs;
  logic int_rcv_clear_clear_qs;
  logic int_rcv_clear_clear_wd;
  logic int_rcv_clear_clear_we;
  logic [30:0] int_rcv_clear_reserved_qs;
  logic [31:0] letter0_qs;
  logic [31:0] letter0_wd;
  logic letter0_we;
  logic [31:0] letter1_qs;
  logic [31:0] letter1_wd;
  logic letter1_we;

  // Register instances
  // R[int_snd_status]: V(False)

  //   F[status]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_int_snd_status_status (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (int_snd_status_status_we),
    .wd     (int_snd_status_status_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.int_snd_status.status.q ),

    // to register interface (read)
    .qs     (int_snd_status_status_qs)
  );


  //   F[reserved]: 31:1
  // constant-only read
  assign int_snd_status_reserved_qs = 31'h0;


  // R[int_snd_set]: V(False)

  //   F[set]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_int_snd_set_set (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (int_snd_set_set_we),
    .wd     (int_snd_set_set_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.int_snd_set.set.q ),

    // to register interface (read)
    .qs     (int_snd_set_set_qs)
  );


  //   F[reserved]: 31:1
  // constant-only read
  assign int_snd_set_reserved_qs = 31'h0;


  // R[int_snd_clear]: V(False)

  //   F[clear]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_int_snd_clear_clear (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (int_snd_clear_clear_we),
    .wd     (int_snd_clear_clear_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.int_snd_clear.clear.q ),

    // to register interface (read)
    .qs     (int_snd_clear_clear_qs)
  );


  //   F[reserved]: 31:1
  // constant-only read
  assign int_snd_clear_reserved_qs = 31'h0;


  // R[int_rcv_status]: V(False)

  //   F[status]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_int_rcv_status_status (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (int_rcv_status_status_we),
    .wd     (int_rcv_status_status_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.int_rcv_status.status.q ),

    // to register interface (read)
    .qs     (int_rcv_status_status_qs)
  );


  //   F[reserved]: 31:1
  // constant-only read
  assign int_rcv_status_reserved_qs = 31'h0;


  // R[int_rcv_set]: V(False)

  //   F[set]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_int_rcv_set_set (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (int_rcv_set_set_we),
    .wd     (int_rcv_set_set_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.int_rcv_set.set.q ),

    // to register interface (read)
    .qs     (int_rcv_set_set_qs)
  );


  //   F[reserved]: 31:1
  // constant-only read
  assign int_rcv_set_reserved_qs = 31'h0;


  // R[int_rcv_clear]: V(False)

  //   F[clear]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_int_rcv_clear_clear (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (int_rcv_clear_clear_we),
    .wd     (int_rcv_clear_clear_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.int_rcv_clear.clear.q ),

    // to register interface (read)
    .qs     (int_rcv_clear_clear_qs)
  );


  //   F[reserved]: 31:1
  // constant-only read
  assign int_rcv_clear_reserved_qs = 31'h0;


  // R[letter0]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_letter0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (letter0_we),
    .wd     (letter0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (letter0_qs)
  );


  // R[letter1]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_letter1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (letter1_we),
    .wd     (letter1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (letter1_qs)
  );




  logic [7:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == MAILBOX_INT_SND_STATUS_OFFSET);
    addr_hit[1] = (reg_addr == MAILBOX_INT_SND_SET_OFFSET);
    addr_hit[2] = (reg_addr == MAILBOX_INT_SND_CLEAR_OFFSET);
    addr_hit[3] = (reg_addr == MAILBOX_INT_RCV_STATUS_OFFSET);
    addr_hit[4] = (reg_addr == MAILBOX_INT_RCV_SET_OFFSET);
    addr_hit[5] = (reg_addr == MAILBOX_INT_RCV_CLEAR_OFFSET);
    addr_hit[6] = (reg_addr == MAILBOX_LETTER0_OFFSET);
    addr_hit[7] = (reg_addr == MAILBOX_LETTER1_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(MAILBOX_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(MAILBOX_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(MAILBOX_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(MAILBOX_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(MAILBOX_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(MAILBOX_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(MAILBOX_PERMIT[6] & ~reg_be))) |
               (addr_hit[7] & (|(MAILBOX_PERMIT[7] & ~reg_be)))));
  end

  assign int_snd_status_status_we = addr_hit[0] & reg_we & !reg_error;
  assign int_snd_status_status_wd = reg_wdata[0];

  assign int_snd_set_set_we = addr_hit[1] & reg_we & !reg_error;
  assign int_snd_set_set_wd = reg_wdata[0];

  assign int_snd_clear_clear_we = addr_hit[2] & reg_we & !reg_error;
  assign int_snd_clear_clear_wd = reg_wdata[0];

  assign int_rcv_status_status_we = addr_hit[3] & reg_we & !reg_error;
  assign int_rcv_status_status_wd = reg_wdata[0];

  assign int_rcv_set_set_we = addr_hit[4] & reg_we & !reg_error;
  assign int_rcv_set_set_wd = reg_wdata[0];

  assign int_rcv_clear_clear_we = addr_hit[5] & reg_we & !reg_error;
  assign int_rcv_clear_clear_wd = reg_wdata[0];

  assign letter0_we = addr_hit[6] & reg_we & !reg_error;
  assign letter0_wd = reg_wdata[31:0];

  assign letter1_we = addr_hit[7] & reg_we & !reg_error;
  assign letter1_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = int_snd_status_status_qs;
        reg_rdata_next[31:1] = int_snd_status_reserved_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = int_snd_set_set_qs;
        reg_rdata_next[31:1] = int_snd_set_reserved_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = int_snd_clear_clear_qs;
        reg_rdata_next[31:1] = int_snd_clear_reserved_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[0] = int_rcv_status_status_qs;
        reg_rdata_next[31:1] = int_rcv_status_reserved_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = int_rcv_set_set_qs;
        reg_rdata_next[31:1] = int_rcv_set_reserved_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = int_rcv_clear_clear_qs;
        reg_rdata_next[31:1] = int_rcv_clear_reserved_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = letter0_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = letter1_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule
