// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package scmi_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } intr;
    struct packed {
      logic [30:0] q;
    } preserve_mask;
  } scmi_reg2hw_doorbell_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } intr;
    struct packed {
      logic [30:0] q;
    } preserve_mask;
  } scmi_reg2hw_completion_interrupt_reg_t;

  // Register -> HW type
  typedef struct packed {
    scmi_reg2hw_doorbell_reg_t doorbell; // [63:32]
    scmi_reg2hw_completion_interrupt_reg_t completion_interrupt; // [31:0]
  } scmi_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SCMI_RESERVED_1_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] SCMI_CHANNEL_STATUS_OFFSET = 6'h 4;
  parameter logic [BlockAw-1:0] SCMI_RESERVED_2_OFFSET = 6'h 8;
  parameter logic [BlockAw-1:0] SCMI_RESERVED_3_OFFSET = 6'h c;
  parameter logic [BlockAw-1:0] SCMI_CHANNEL_FLAGS_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] SCMI_LENGTH_OFFSET = 6'h 14;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_HEADER_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] SCMI_MESSAGE_PAYLOAD_1_OFFSET = 6'h 1c;
  parameter logic [BlockAw-1:0] SCMI_DOORBELL_OFFSET = 6'h 20;
  parameter logic [BlockAw-1:0] SCMI_COMPLETION_INTERRUPT_OFFSET = 6'h 24;

  // Register index
  typedef enum int {
    SCMI_RESERVED_1,
    SCMI_CHANNEL_STATUS,
    SCMI_RESERVED_2,
    SCMI_RESERVED_3,
    SCMI_CHANNEL_FLAGS,
    SCMI_LENGTH,
    SCMI_MESSAGE_HEADER,
    SCMI_MESSAGE_PAYLOAD_1,
    SCMI_DOORBELL,
    SCMI_COMPLETION_INTERRUPT
  } scmi_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SCMI_PERMIT [10] = '{
    4'b 0000, // index[0] SCMI_RESERVED_1
    4'b 0000, // index[1] SCMI_CHANNEL_STATUS
    4'b 0000, // index[2] SCMI_RESERVED_2
    4'b 0000, // index[3] SCMI_RESERVED_3
    4'b 0000, // index[4] SCMI_CHANNEL_FLAGS
    4'b 0000, // index[5] SCMI_LENGTH
    4'b 0000, // index[6] SCMI_MESSAGE_HEADER
    4'b 0000, // index[7] SCMI_MESSAGE_PAYLOAD_1
    4'b 0000, // index[8] SCMI_DOORBELL
    4'b 0000  // index[9] SCMI_COMPLETION_INTERRUPT
  };

endpackage

